-- Revising the Select Query I
-- 중복조건이 핵심
SELECT * FROM CITY WHERE POPULATION > 100000 AND COUNTRYCODE='USA';

-- Revising the Select Query II
-- 위 문제에 추가하여 컬럼 선택
SELECT NAME FROM CITY WHERE POPULATION > 120000 AND COUNTRYCODE='USA';

-- SELECT ALL
SELECT * FROM CITY;

-- Select By ID
SELECT * FROM CITY WHERE ID=1661;

-- Japanese Cities' Attributes
SELECT * FROM CITY WHERE COUNTRYCODE='JPN';

-- Japanese Cities' Names
SELECT NAME FROM CITY WHERE COUNTRYCODE='JPN';

-- Weather Observation Station 1
SELECT CITY, STATE FROM STATION;

-- Weather Observation Station 3
SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0;

-- Weather Observation Station 4
-- 서브쿼리 활용해야함. 죄다 SELECT로 처리하는게 마치 타입 연산처럼 느껴짐.
SELECT \
  (SELECT COUNT(CITY) FROM STATION) \
  - \
  (SELECT COUNT(DISTINCT CITY) FROM STATION) \ 
  AS DIFFER;

-- Weather Observation Station 5
-- UNION과 다중조건 ORDER BY, LIMIT
(SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY), CITY LIMIT 1) \
UNION \
(SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC LIMIT 1); 

